### ISSUE TITLE
Feature: User can display a list of items from a search

### ISSUE THREAD

**Issue by jonathanphtran** [jonathanphtran/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search by food drink or name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user searches for a food or drink, a list of items with similar or exact names will be shown.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![search-feature-desktop](https://user-images.githubusercontent.com/65892780/121268072-117a8080-c872-11eb-9055-5ed00a0779f1.png)
![search-feature-mobile](https://user-images.githubusercontent.com/65892780/121268115-25be7d80-c872-11eb-9d29-ca39cd803234.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the html layout 
- [x] Design the CSS layout
- [x] Make sure it looks good on mobile and desktop
- [x] Get value from searches
- [x] Get list of food items from the food database API
- [x] Display a list of items
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
